name: Build all binary for collecting domains
on:
  workflow_dispatch:
  schedule:
  - cron: "00 16 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
          go-version: 1.20.2
    - name: Build all
      run: |
       go install github.com/d3mondev/puredns/v2@latest
       echo "starting amass"
       go get -v github.com/OWASP/Amass/v3/...
       go get -u github.com/tomnomnom/anew
       echo "starting nuclei"
       go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
       echo "starting subfinder"
       go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
      working-directory: /home/runner/work/updaterecon 
    - name: Copy all
      run: |
       git config --global user.name "Github Actions";git config --global user.email "actions@github.com"
       git clone https://${{ secrets.tok}}@github.com/wanted1205/domainrecon.git
       cp -r /home/runner/go/bin/. /home/runner/work/updaterecon/domainrecon/bin/;rm -rf /home/runner/work/updaterecon/domainrecon/bin/examples
      working-directory: /home/runner/work/updaterecon
    - name: Push to repo
      run: |
       git add bin/
       git commit -m "Update bin" -a
       git push "https://${{ secrets.tok }}@github.com/wanted1205/domainrecon.git" HEAD:master --follow-tags
      working-directory: /home/runner/work/updaterecon/domainrecon 
