name: Build all binary
on:
  workflow_dispatch:
  schedule:
  - cron: "30 16 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
          go-version: 1.17
    - name: Setup All
      run: |
         git clone https://github.com/hahwul/dalfox;git clone https://github.com/ffuf/ffuf;git clone https://github.com/hakluke/hakrawler
      working-directory: /home/runner/work/updaterecon
    - name: Build all
      run: |
       echo "starting shuffledns"
       GO111MODULE=on go get -v github.com/projectdiscovery/shuffledns/cmd/shuffledns
       echo "starting amass"
       go get -v github.com/OWASP/Amass/v3/...
       echo "starting httpx"
       go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
       echo "starting dalfox"
       cd dalfox;go build .;cd ..
       echo "starting ffuf"
       cd ffuf;go build .;cd ..
       echo "starting hakrawler"
       cd hakrawler;go build .;cd ..
       echo "starting nuclei"
       go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
       echo "starting subfinder"
       go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
      working-directory: /home/runner/work/updaterecon 
    - name: Copy all
      run: |
       git config --global user.name "Github Actions";git config --global user.email "actions@github.com"
       git clone https://${{ secrets.tok}}@github.com/wanted1205/recon.git
       git clone https://${{ secrets.tok}}@github.com/wanted1205/1recon.git
       echo "copying dalfox"
       cp dalfox/dalfox recon/bin/;cp ffuf/ffuf recon/bin/;cp hakrawler/hakrawler recon/bin/
       echo "copying go binary"
       cp -r /home/runner/go/bin/. /home/runner/work/updaterecon/1recon/bin/
       cp -r /home/runner/go/bin/. /home/runner/work/updaterecon/recon/bin/
       cp dalfox/dalfox 1recon/bin/;cp ffuf/ffuf 1recon/bin/;cp hakrawler/hakrawler 1recon/bin/
      working-directory: /home/runner/work/updaterecon
    - name: Push to repo
      run: |
       git add bin/
       git commit -m "Update bin" -a
       git push "https://${{ secrets.tok }}@github.com/wanted1205/1recon.git" HEAD:master --follow-tags
      working-directory: /home/runner/work/updaterecon/1recon 
    - name: Push to repo
      run: |
       git add bin/
       git commit -m "Update bin" -a
       git push "https://${{ secrets.tok }}@github.com/wanted1205/recon.git" HEAD:main --follow-tags
      working-directory: /home/runner/work/updaterecon/recon 
