name: Build all binary
#on:
#  schedule:
#  - cron: "30 16 * * *"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2.1.4
    - name: Setup All
      run: |
       sudo apt-get install libldns-dev -y
       git clone https://github.com/blechschmidt/massdns;git clone https://github.com/hahwul/dalfox;git clone https://github.com/ffuf/ffuf;git clone https://github.com/lc/gau/;git clone https://github.com/tomnomnom/gf;git clone https://github.com/hakluke/hakrawler;git clone https://github.com/projectdiscovery/nuclei;git clone https://github.com/projectdiscovery/subfinder;git clone https://github.com/tomnomnom/waybackurls
      working-directory: /home/runner/work/updaterecon
    - name: Build all
      run: |
       GO111MODULE=on go get -v github.com/projectdiscovery/shuffledns/cmd/shuffledns
       GO111MODULE=on go get -v github.com/OWASP/Amass/v3/...
       GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx
       cd massdns;make;cd ..
       cd anew;go build .;cd ..
       cd dalfox;go build .;cd ..
       cd ffuf;go build .;cd ..
       cd gau;go build .;cd ..
       cd gf;go build .;cd ..
       cd hakrawler;go build .;cd ..
       cd nuclei/v2/cmd/nuclei/;go build .;cd ../../../../
       cd subfinder/v2/cmd/subfinder;go build . ;cd ../../../../
       cd waybackurls;go build .;cd ..
      working-directory: /home/runner/work/updaterecon 
    - name: Copy all
      run: |
       git clone https://${{ secrets.tok}}@github.com/wanted1205/1recon.git
       cp massdns/bin/massdns 1recon/bin/
       cp  /home/runner/go/bin/shuffledns /home/runner/work/updaterecon/1recon/bin/;cp  /home/runner/go/bin/amass /home/runner/work/updaterecon/1recon/bin/;cp  /home/runner/go/bin/httpx /home/runner/work/updaterecon/1recon/bin/
       cp dalfox/dalfox 1recon/bin/;cp ffuf/ffuf 1recon/bin/;cp hakrawler/hakrawler 1recon/bin/;cp gau/gau 1recon/bin/;cp gf/gf 1recon/bin/;cp nuclei/v2/cmd/nuclei/nuclei 1recon/bin/;cp subfinder/v2/cmd/subfinder/subfinder 1recon/bin/;cp waybackurls/waybackurls 1recon/bin/
      working-directory: /home/runner/work/updaterecon
    - name: Push to repo
      run: |
       git clone https://${{ secrets.tok }}@github.com/wanted1205/1recon.git
       git config --global user.name "Github Actions";git config --global user.email "actions@github.com"
       git add bin/
       git commit -m "Update bin" -a
       git push "https://${{ secrets.tok }}@github.com/wanted1205/1recon.git" HEAD:master --follow-tags
      working-directory: /home/runner/work/updaterecon/1recon 
