name: Update resolvers

on:
  schedule:
   - cron:  '00 00,06,12,18 * * *' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: dnsvalidator
      run: |
        git clone https://github.com/vortexau/dnsvalidator
        cd dnsvalidator
        git config --global user.name "Github Actions";git config --global user.email "actions@github.com"
        pip3 install wheel
        pip3 install setuptools
        sudo python3 setup.py install
        dnsvalidator -tL https://raw.githubusercontent.com/wanted1205/updaterecon/main/resolvers.txt -threads 5 -o ../resolvers.txt
        #dnsvalidator -tL https://raw.githubusercontent.com/proabiral/Fresh-Resolvers/master/resolvers.ipv6 -threads 5 -o ../resolvers.txt
        #dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 5 -o ../resolvers.txt
        #dnsvalidator -tL https://raw.githubusercontent.com/proabiral/Fresh-Resolvers/master/resolvers.txt -threads 5 -o ../resolvers.txt
        #dnsvalidator -tL https://raw.githubusercontent.com/blechschmidt/massdns/master/lists/resolvers.txt -threads 5 -o ../resolvers.txt
        sed -i '/^$/d' ../resolvers.txt;cd ..
        cat resolvers.txt|sort|uniq>>resolvers1.txt;mv resolvers1.txt resolvers.txt
    - name: Commit resolvers.txt
      run: |
        echo "complete here";ls
        git clone https://${{ secrets.tok }}@github.com/wanted1205/1recon.git
        git clone https://${{ secrets.tok }}@github.com/wanted1205/recon.git
        git clone https://${{ secrets.tok }}@github.com/wanted1205/updaterecon.git
        cp resolvers.txt 1recon/resolvers.txt;cp resolvers.txt recon/resolvers.txt;cp resolvers.txt updaterecon/resolvers.txt
        cd 1recon;ls;git add resolvers.txt;git commit -m "Update resolvers" -a;git push "https://${{ secrets.tok }}@github.com/wanted1205/1recon.git" HEAD:master --follow-tags;cd ..
        cd recon;ls;git add resolvers.txt;git commit -m "Update resolvers" -a;git push "https://${{ secrets.tok }}@github.com/wanted1205/recon.git" HEAD:main --follow-tags;cd ..
        cd updaterecon;ls;git add resolvers.txt;git commit -m "Update resolvers" -a;git push "https://${{ secrets.tok }}@github.com/wanted1205/updaterecon.git" HEAD:main --follow-tags
