name: Build all binary
on:
  workflow_dispatch:
  schedule:
  - cron: "30 16 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      run: |
         wget https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
         sudo rm -rf /usr/local/go &&sudo tar -C /usr/local -xzf go1.17.2.linux-amd64.tar.gz
         export PATH=$PATH:/usr/local/go/bin
    - name: Setup All
      run: |
       sudo apt-get install libldns-dev -y
       git clone https://github.com/blechschmidt/massdns;git clone https://github.com/hahwul/dalfox;git clone https://github.com/ffuf/ffuf;git clone https://github.com/lc/gau/;git clone https://github.com/tomnomnom/gf;git clone https://github.com/hakluke/hakrawler;git clone https://github.com/projectdiscovery/nuclei;git clone https://github.com/projectdiscovery/subfinder;git clone https://github.com/tomnomnom/waybackurls
      working-directory: /home/runner/work/updaterecon
    - name: Build all
      run: |
       export PATH=$PATH:/usr/local/go/bin
       GO111MODULE=on go get -v github.com/projectdiscovery/shuffledns/cmd/shuffledns
       go get -v github.com/OWASP/Amass/v3/...
       GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx
       cd massdns;make;cd ..
       cd dalfox;go build .;cd ..
       cd ffuf;go build .;cd ..
       cd gau;go build .;cd ..
       cd gf;go build .;cd ..
       cd hakrawler;go build .;cd ..
       go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
       cd subfinder/v2/cmd/subfinder;go build . ;cd ../../../../
       cd waybackurls;go build .;cd ..
      working-directory: /home/runner/work/updaterecon 
    - name: Copy all
      run: |
       git config --global user.name "Github Actions";git config --global user.email "actions@github.com"
       git clone https://${{ secrets.tok}}@github.com/wanted1205/recon.git
       git clone https://${{ secrets.tok}}@github.com/wanted1205/1recon.git
       cp massdns/bin/massdns 1recon/bin/;cp massdns/bin/massdns recon/bin/;cd /home/runner/go/bin/;ls;cd ..;ls;cd /home/runner/work/updaterecon
       cp dalfox/dalfox recon/bin/;cp ffuf/ffuf recon/bin/;cp hakrawler/hakrawler recon/bin/;cp gau/gau recon/bin/;cp gf/gf recon/bin/;cp subfinder/v2/cmd/subfinder/subfinder recon/bin/;cp waybackurls/waybackurls recon/bin/
       cp  /home/runner/go/bin/shuffledns /home/runner/work/updaterecon/recon/bin/;cp  $GOPATH/bin/amass /home/runner/work/updaterecon/recon/bin/;cp  /home/runner/go/bin/httpx /home/runner/work/updaterecon/recon/bin/ cp  /home/runner/go/bin/nuclei /home/runner/work/updaterecon/recon/bin/
       cp  /home/runner/go/bin/shuffledns /home/runner/work/updaterecon/1recon/bin/;cp  $GOPATH/bin/amass /home/runner/work/updaterecon/1recon/bin/;cp  /home/runner/go/bin/httpx /home/runner/work/updaterecon/1recon/bin/ cp  /home/runner/go/bin/nuclei /home/runner/work/updaterecon/1recon/bin/
       cp dalfox/dalfox 1recon/bin/;cp ffuf/ffuf 1recon/bin/;cp hakrawler/hakrawler 1recon/bin/;cp gau/gau 1recon/bin/;cp gf/gf 1recon/bin/;cp subfinder/v2/cmd/subfinder/subfinder 1recon/bin/;cp waybackurls/waybackurls 1recon/bin/
      working-directory: /home/runner/work/updaterecon
    - name: Push to repo
      run: |
       git add bin/
       git commit -m "Update bin" -a
       git push "https://${{ secrets.tok }}@github.com/wanted1205/1recon.git" HEAD:master --follow-tags
      working-directory: /home/runner/work/updaterecon/1recon 
    - name: Push to repo
      run: |
       git add bin/
       git commit -m "Update bin" -a
       git push "https://${{ secrets.tok }}@github.com/wanted1205/recon.git" HEAD:main --follow-tags
      working-directory: /home/runner/work/updaterecon/recon 
