name: Update resolvers

#on:
#  schedule:
#  - cron:  '00 00 * * *'
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: dnsvalidator
      run: |
        git clone https://github.com/vortexau/dnsvalidator
        cd dnsvalidator
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        pip3 install wheel
        pip3 install setuptools
        sudo python3 setup.py install
        #dnsvalidator -tL https://raw.githubusercontent.com/proabiral/Fresh-Resolvers/master/resolvers.ipv6 -threads 5 -o ../resolvers.txt
        #dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 5 -o ../resolvers.txt
        #dnsvalidator -tL https://raw.githubusercontent.com/proabiral/Fresh-Resolvers/master/resolvers.txt -threads 5 -o ../resolvers.txt
        dnsvalidator -tL https://raw.githubusercontent.com/blechschmidt/massdns/master/lists/resolvers.txt -threads 5 -o ../resolvers.txt
        sed -i '/^$/d' ../resolvers.txt
        sort -uR ../resolvers.txt -o ../resolvers.txt
    - name: Commit resolvers.txt
      run: |
        git clone https://${{ secrets.tok }}@github.com/wanted1205/1recon.git
        git clone https://${{ secrets.tok }}@github.com/wanted1205/recon.git
        cp resolvers.txt 1recon/resolvers.txt;cp resolvers.txt recon/resolvers.txt 
        cd 1recon;ls;git add resolvers.txt;git commit -m "Update resolvers" -a;git push "https://${{ secrets.tok }}@github.com/wanted1205/1recon.git" HEAD:master --follow-tags;cd ..
        cd recon;ls;git add resolvers.txt;git commit -m "Update resolvers" -a;git push "https://${{ secrets.tok }}@github.com/wanted1205/recon.git" HEAD:main --follow-tags

 
