name: Build all binary for vuln recon
on:
  workflow_dispatch:
  schedule:
  - cron: "00 15 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
          go-version: 1.19
    - name: Build all
      run: |
       go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
       go get -u github.com/tomnomnom/httprobe
      working-directory: /home/runner/work/updaterecon 
    - name: Copy all
      run: |
       git config --global user.name "Github Actions";git config --global user.email "actions@github.com"
       git clone https://${{ secrets.tok}}@github.com/wanted1205/vulnrecon.git
       cp -r /home/runner/go/bin/. /home/runner/work/updaterecon/vulnrecon/bin/;rm -rf /home/runner/work/updaterecon/vulnrecon/bin/examples
      working-directory: /home/runner/work/updaterecon
    - name: Push to repo
      run: |
       git add bin/
       git commit -m "Update bin" -a
       git push "https://${{ secrets.tok }}@github.com/wanted1205/vulnrecon.git" HEAD:master --follow-tags
      working-directory: /home/runner/work/updaterecon/vulnrecon 
